import { character } from "./type";

export const characters: character[] = [
  { element: "fire", star: 5, name_en: "Vagner", name_ko: "바그너" },
  { element: "fire", star: 5, name_en: "Marina", name_ko: "마리나" },
  { element: "fire", star: 5, name_en: "Clarisse", name_ko: "클라리스" },
  {
    element: "fire",
    star: 5,
    name_en: "Marianne_Christmas",
    name_ko: "마리안네(크리스마스)",
  },
  { element: "fire", star: 5, name_en: "Kikuno", name_ko: "키쿠노" },
  { element: "fire", star: 5, name_en: "Noenne", name_ko: "노에네" },
  { element: "fire", star: 5, name_en: "Rolf", name_ko: "롤프" },
  { element: "fire", star: 5, name_en: "Mia_Summer", name_ko: "미아" },
  { element: "water", star: 5, name_en: "Sonia", name_ko: "소냐" },
  { element: "water", star: 5, name_en: "Suizen", name_ko: "스이젠" },
  {
    element: "water",
    star: 5,
    name_en: "Ellya_Newyear",
    name_ko: "에리야(신년)",
  },
  { element: "water", star: 5, name_en: "Cipher", name_ko: "사이퍼" },
  { element: "water", star: 5, name_en: "Selene", name_ko: "시렌" },
  { element: "water", star: 5, name_en: "Remnith", name_ko: "림니스" },
  { element: "water", star: 5, name_en: "Rakisha", name_ko: "라키샤" },
  { element: "thunder", star: 5, name_en: "Inaho", name_ko: "이나호" },
  {
    element: "thunder",
    star: 5,
    name_en: "Cagliostro",
    name_ko: "칼리오스트로",
  },
  {
    element: "thunder",
    star: 5,
    name_en: "Soushiro_Christmas",
    name_ko: "소우시로(크리스마스)",
  },
  { element: "thunder", star: 5, name_en: "Metis", name_ko: "메티스" },
  { element: "thunder", star: 5, name_en: "Barrek", name_ko: "버락" },
  { element: "thunder", star: 5, name_en: "Sera", name_ko: "세라" },
  { element: "thunder", star: 5, name_en: "Botan", name_ko: "보탄" },
  {
    element: "thunder",
    star: 5,
    name_en: "Illumine_Summer",
    name_ko: "이루미(수영복)",
  },
  {
    element: "thunder",
    star: 5,
    name_en: "Belsidia_Summer",
    name_ko: "베르세티아(수영복)",
  },
  { element: "wind", star: 5, name_en: "Celtie", name_ko: "실티" },
  { element: "wind", star: 5, name_en: "Phiria", name_ko: "필리아" },
  { element: "wind", star: 5, name_en: "Murakumo", name_ko: "무라쿠모" },
  { element: "wind", star: 5, name_en: "Leon", name_ko: "레온" },
  { element: "wind", star: 5, name_en: "Shywe", name_ko: "시우에" },
  { element: "wind", star: 5, name_en: "Miguel", name_ko: "미겔" },
  { element: "wind", star: 5, name_en: "Kokkoro", name_ko: "콧코로" },
  { element: "wind", star: 5, name_en: "Schult", name_ko: "슐트" },
  { element: "light", star: 5, name_en: "Nephtim", name_ko: "네프팀" },
  { element: "light", star: 5, name_en: "Razelt", name_ko: "라젤트" },
  { element: "light", star: 5, name_en: "Eclair", name_ko: "에크릴" },

  {
    element: "light",
    star: 5,
    name_en: "Inaho_Christmas",
    name_ko: "이나호(크리스마스)",
  },
  { element: "light", star: 5, name_en: "Teurgis", name_ko: "타제스" },
  { element: "light", star: 5, name_en: "Bulleta", name_ko: "바렛타" },
  { element: "light", star: 5, name_en: "Libram", name_ko: "리브람" },
  {
    element: "light",
    star: 5,
    name_en: "Nephtim_Half",
    name_ko: "네프팀(축제)",
  },
  { element: "light", star: 5, name_en: "Pecorine", name_ko: "페코린느" },
  { element: "light", star: 5, name_en: "Lyra", name_ko: "리라" },
  { element: "dark", star: 5, name_en: "Belsidia", name_ko: "베르세티아" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "베론" },
  { element: "dark", star: 5, name_en: "Mormia", name_ko: "모르미아" },
  { element: "dark", star: 5, name_en: "Carla", name_ko: "카라" },
  { element: "dark", star: 5, name_en: "Olivia", name_ko: "올리비에" },
  { element: "dark", star: 5, name_en: "Karyl", name_ko: "캬루" },
  {
    element: "dark",
    star: 5,
    name_en: "Alice_Summer",
    name_ko: "앨리스(수영복)",
  },
  { element: "fire", star: 4, name_en: "Alk", name_ko: "아르크" },
  { element: "fire", star: 4, name_en: "Azel", name_ko: "아젤" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "비앙카" },
  { element: "fire", star: 4, name_en: "Hanabi", name_ko: "하나비" },
  { element: "fire", star: 4, name_en: "Asukirimaru", name_ko: "아스키리마루" },
  { element: "fire", star: 4, name_en: "Clyde", name_ko: "글라이드" },
  { element: "fire", star: 4, name_en: "Kannon", name_ko: "카논" },
  {
    element: "fire",
    star: 4,
    name_en: "Luluca_Newyear",
    name_ko: "류류카(신년)",
  },
  { element: "fire", star: 4, name_en: "Levy", name_ko: "레비" },
  { element: "fire", star: 4, name_en: "Kyrie", name_ko: "키리" },
  { element: "fire", star: 4, name_en: "Hayz", name_ko: "헤이즈" },
  { element: "fire", star: 4, name_en: "Melmyna", name_ko: "밀미나" },
  { element: "water", star: 4, name_en: "Yuwel", name_ko: "유웰" },
  { element: "water", star: 4, name_en: "Liesel", name_ko: "리젤" },
  { element: "water", star: 4, name_en: "Amelia", name_ko: "아멜리아" },
  { element: "water", star: 4, name_en: "Alice", name_ko: "앨리스" },
  { element: "water", star: 4, name_en: "Sharon", name_ko: "샤론" },
  { element: "water", star: 4, name_en: "Rain", name_ko: "라나" },
  { element: "water", star: 4, name_en: "Saar", name_ko: "자르" },
  { element: "water", star: 4, name_en: "Mordiaga", name_ko: "모르디아가" },
  { element: "water", star: 4, name_en: "Mizuchi", name_ko: "미즈치" },
  { element: "water", star: 4, name_en: "Sohvi", name_ko: "소비" },
  {
    element: "water",
    star: 4,
    name_en: "Gerard_Summer",
    name_ko: "제랄(수영복)",
  },
  {
    element: "water",
    star: 4,
    name_en: "Marina_Summer",
    name_ko: "마리나(수영복)",
  },
  { element: "thunder", star: 4, name_en: "Rams", name_ko: "람스" },
  { element: "thunder", star: 4, name_en: "Renoir", name_ko: "루나르" },
  { element: "thunder", star: 4, name_en: "Regis", name_ko: "레지스" },
  { element: "thunder", star: 4, name_en: "Eleanor", name_ko: "에렌노르" },
  { element: "thunder", star: 4, name_en: "Jay", name_ko: "제이" },
  { element: "thunder", star: 4, name_en: "Mino", name_ko: "미노" },
  {
    element: "thunder",
    star: 4,
    name_en: "Aureo_Christmas",
    name_ko: "아우레오(크리스마스)",
  },
  { element: "thunder", star: 4, name_en: "Adonis", name_ko: "아도니" },
  { element: "thunder", star: 4, name_en: "Rudy", name_ko: "루디" },
  {
    element: "thunder",
    star: 4,
    name_en: "Naska_Summer",
    name_ko: "네스카(수영복)",
  },
  { element: "thunder", star: 4, name_en: "Roselia", name_ko: "로제리야" },
  { element: "wind", star: 4, name_en: "Nimbus", name_ko: "시로" },
  { element: "wind", star: 4, name_en: "Mia", name_ko: "미아" },
  { element: "wind", star: 4, name_en: "Aurore", name_ko: "오로울" },
  { element: "wind", star: 4, name_en: "Soushiro", name_ko: "소우시로" },
  { element: "wind", star: 4, name_en: "Melsele", name_ko: "멜스루" },
  { element: "wind", star: 4, name_en: "Helga", name_ko: "헬가" },
  { element: "wind", star: 4, name_en: "Arisa", name_ko: "아리사" },
  {
    element: "wind",
    star: 4,
    name_en: "Rebecca_Newyear",
    name_ko: "레베카(신년)",
  },
  { element: "wind", star: 4, name_en: "Lou", name_ko: "루" },
  { element: "wind", star: 4, name_en: "Suzuka", name_ko: "스즈카" },
  { element: "wind", star: 4, name_en: "Kohane", name_ko: "코하네" },
  { element: "light", star: 4, name_en: "Dia", name_ko: "디어" },
  { element: "light", star: 4, name_en: "Gerard", name_ko: "제랄" },
  { element: "light", star: 4, name_en: "Ellya", name_ko: "에리야" },
  { element: "light", star: 4, name_en: "Finn", name_ko: "핀" },
  { element: "light", star: 4, name_en: "Keira", name_ko: "키라" },
  { element: "light", star: 4, name_en: "Parfait", name_ko: "파르페" },
  { element: "light", star: 4, name_en: "Illumine", name_ko: "이루미" },
  { element: "light", star: 4, name_en: "Hopper", name_ko: "호플" },
  { element: "light", star: 4, name_en: "Lyla", name_ko: "라이아" },
  { element: "light", star: 4, name_en: "Floretta", name_ko: "플로렛타" },
  {
    element: "light",
    star: 4,
    name_en: "Liesel_Summer",
    name_ko: "리젤(수영복)",
  },
  { element: "light", star: 4, name_en: "Keyana", name_ko: "키아나" },
  { element: "dark", star: 4, name_en: "Arum", name_ko: "아름" },
  { element: "dark", star: 4, name_en: "Marianne", name_ko: "마리안네" },
  { element: "dark", star: 4, name_en: "Andy", name_ko: "앤디" },
  { element: "dark", star: 4, name_en: "Liam", name_ko: "리안" },
  { element: "dark", star: 4, name_en: "Yuwel_Newyear", name_ko: "유웰(신년)" },
  { element: "dark", star: 4, name_en: "Quazer", name_ko: "쿼처" },
  { element: "dark", star: 4, name_en: "Love", name_ko: "라브" },
  { element: "dark", star: 4, name_en: "Selgir", name_ko: "셀지르" },
  { element: "dark", star: 4, name_en: "Luna", name_ko: "루나" },
  {
    element: "dark",
    star: 4,
    name_en: "Marguerite_Summer",
    name_ko: "마르그리트(수영복)",
  },
  { element: "fire", star: 3, name_en: "Lilial", name_ko: "리릴" },
  { element: "fire", star: 3, name_en: "Marnie", name_ko: "메이미" },
  { element: "fire", star: 3, name_en: "Elise", name_ko: "이리스" },
  { element: "fire", star: 3, name_en: "Haaj", name_ko: "허쉬" },
  { element: "fire", star: 3, name_en: "Jin", name_ko: "진" },
  { element: "fire", star: 3, name_en: "Trine", name_ko: "트레이네" },
  { element: "fire", star: 3, name_en: "Gilasrad", name_ko: "길슬롯" },
  { element: "fire", star: 3, name_en: "Enni", name_ko: "엔니" },
  { element: "fire", star: 3, name_en: "Jake", name_ko: "제이크" },
  { element: "fire", star: 3, name_en: "Cran", name_ko: "쿠란" },
  { element: "fire", star: 3, name_en: "Harlisha", name_ko: "하리사" },
  { element: "fire", star: 3, name_en: "Sven", name_ko: "스벤" },
  { element: "water", star: 3, name_en: "Keylos", name_ko: "케일로스" },
  { element: "water", star: 3, name_en: "Trista", name_ko: "트리스타" },
  { element: "water", star: 3, name_en: "Walter", name_ko: "발터" },
  { element: "water", star: 3, name_en: "Elza", name_ko: "엘자" },
  { element: "water", star: 3, name_en: "Klaus", name_ko: "클라우스" },
  { element: "water", star: 3, name_en: "Shirano", name_ko: "시라노" },
  { element: "water", star: 3, name_en: "Kaiyu", name_ko: "카이유" },
  { element: "water", star: 3, name_en: "Lassie", name_ko: "랏티" },
  { element: "water", star: 3, name_en: "Faf", name_ko: "파프" },
  { element: "water", star: 3, name_en: "Rico", name_ko: "리코" },
  {
    element: "water",
    star: 3,
    name_en: "Challua_Christmas",
    name_ko: "챠루아(크리스마스)",
  },
  { element: "water", star: 3, name_en: "Clara", name_ko: "클라라" },
  { element: "water", star: 3, name_en: "Samantha", name_ko: "사마사" },
  { element: "water", star: 3, name_en: "Ritta", name_ko: "릿타" },
  { element: "thunder", star: 3, name_en: "Yuna", name_ko: "유나" },
  { element: "thunder", star: 3, name_en: "Bonnie", name_ko: "호니" },
  { element: "thunder", star: 3, name_en: "Taiga", name_ko: "타이가" },
  { element: "thunder", star: 3, name_en: "Claw", name_ko: "쿠로" },
  { element: "thunder", star: 3, name_en: "Albert", name_ko: "알베르토" },
  { element: "thunder", star: 3, name_en: "Kazuchi", name_ko: "카즈치" },
  { element: "thunder", star: 3, name_en: "Tatiana", name_ko: "타티아나" },
  { element: "thunder", star: 3, name_en: "Colt", name_ko: "콜트" },
  { element: "thunder", star: 3, name_en: "Shasuzu", name_ko: "샤스스" },
  { element: "thunder", star: 3, name_en: "Fiora", name_ko: "포우라" },
  { element: "thunder", star: 3, name_en: "Mew_Newyear", name_ko: "뮤" },
  { element: "thunder", star: 3, name_en: "Vargen", name_ko: "바루겐" },
  { element: "thunder", star: 3, name_en: "Flana", name_ko: "플라나" },
  { element: "wind", star: 3, name_en: "Evan", name_ko: "에반" },
  { element: "wind", star: 3, name_en: "Challua", name_ko: "챠루아" },
  { element: "wind", star: 3, name_en: "Regitare", name_ko: "레시탈" },
  { element: "wind", star: 3, name_en: "Naska", name_ko: "네스카" },
  { element: "wind", star: 3, name_en: "Mew", name_ko: "뮤" },
  { element: "wind", star: 3, name_en: "Folus", name_ko: "폴스" },
  { element: "wind", star: 3, name_en: "Hartlief", name_ko: "하트리프" },
  { element: "wind", star: 3, name_en: "Conner", name_ko: "코너" },
  { element: "wind", star: 3, name_en: "Jester", name_ko: "재스터" },
  { element: "wind", star: 3, name_en: "Kate", name_ko: "케이트" },
  { element: "wind", star: 3, name_en: "Nellie", name_ko: "네티" },
  { element: "light", star: 3, name_en: "Corinna", name_ko: "코리나" },
  { element: "light", star: 3, name_en: "Marguerite", name_ko: "마르그리트" },
  { element: "light", star: 3, name_en: "Cecilia", name_ko: "세실리아" },
  { element: "light", star: 3, name_en: "Aureo", name_ko: "아우레오" },
  { element: "light", star: 3, name_en: "Raul", name_ko: "라울" },
  { element: "light", star: 3, name_en: "Miles", name_ko: "밀레스" },
  { element: "light", star: 3, name_en: "Luluca", name_ko: "류류카" },
  { element: "light", star: 3, name_en: "Kharo", name_ko: "카로" },
  { element: "dark", star: 3, name_en: "Falsche", name_ko: "파르체" },
  { element: "dark", star: 3, name_en: "Jalil", name_ko: "자릴" },
  { element: "dark", star: 3, name_en: "Arly", name_ko: "아리" },
  { element: "dark", star: 3, name_en: "Shion", name_ko: "시온" },
  { element: "dark", star: 3, name_en: "Adil", name_ko: "아딜" },
  { element: "dark", star: 3, name_en: "Dorothea", name_ko: "도로시아" },
  { element: "dark", star: 3, name_en: "Rebecca", name_ko: "레베카" },
  { element: "dark", star: 3, name_en: "Nochel", name_ko: "노셀" },
  { element: "dark", star: 3, name_en: "Meryll", name_ko: "메릴" },
];
