import { character } from "./type";

export const characters: character[] = [
  { element: "fire", star: 5, name_en: "Clarisse", name_ko: "클라리스" },
  { element: "fire", star: 5, name_en: "Marina", name_ko: "마리나" },
  { element: "fire", star: 5, name_en: "Marina", name_ko: "바그너" },
  {
    element: "fire",
    star: 5,
    name_en: "Marina",
    name_ko: "마리안네(크리스마스)",
  },
  { element: "fire", star: 5, name_en: "Marina", name_ko: "노에네" },
  { element: "fire", star: 5, name_en: "Marina", name_ko: "롤프" },
  { element: "fire", star: 5, name_en: "Marina", name_ko: "키쿠노" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "스이젠" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "소냐" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "에리야(신년)" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "사이퍼" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "시렌" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "림니스" },
  { element: "water", star: 5, name_en: "Marina", name_ko: "라키샤" },
  { element: "thunder", star: 5, name_en: "Marina", name_ko: "칼리오스트로" },
  { element: "thunder", star: 5, name_en: "Marina", name_ko: "이나호" },
  {
    element: "thunder",
    star: 5,
    name_en: "Marina",
    name_ko: "소우시로(크리스마스)",
  },
  { element: "thunder", star: 5, name_en: "Marina", name_ko: "메티스" },
  { element: "thunder", star: 5, name_en: "Marina", name_ko: "버락" },
  { element: "thunder", star: 5, name_en: "Marina", name_ko: "세라" },
  { element: "thunder", star: 5, name_en: "Marina", name_ko: "보탄" },
  { element: "wind", star: 5, name_en: "Marina", name_ko: "레온" },
  { element: "wind", star: 5, name_en: "Marina", name_ko: "무라쿠모" },
  { element: "wind", star: 5, name_en: "Marina", name_ko: "필리아" },
  { element: "wind", star: 5, name_en: "Marina", name_ko: "실티" },
  { element: "wind", star: 5, name_en: "Marina", name_ko: "시우에" },
  { element: "wind", star: 5, name_en: "Marina", name_ko: "미겔" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "에크릴" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "라젤트" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "네프팀" },
  {
    element: "light",
    star: 5,
    name_en: "Marina",
    name_ko: "이나호(크리스마스)",
  },
  { element: "light", star: 5, name_en: "Marina", name_ko: "타제스" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "바렛타" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "리브람" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "네프팀(축제)" },
  { element: "light", star: 5, name_en: "Marina", name_ko: "페코린느" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "베론" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "베르세티아" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "모르미아" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "카라" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "올리비에" },
  { element: "dark", star: 5, name_en: "Vyron", name_ko: "캬루" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "글라이드" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "아스키리마루" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "비앙카" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "아젤" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "아르크" },
  { element: "fire", star: 4, name_en: "Bianca", name_ko: "카논" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "라나" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "샤론" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "앨리스" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "아멜리아" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "리젤" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "유웰" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "모르디아가" },
  { element: "water", star: 4, name_en: "Bianca", name_ko: "소비" },
  { element: "thunder", star: 4, name_en: "Bianca", name_ko: "미노" },
  { element: "thunder", star: 4, name_en: "Bianca", name_ko: "제이" },
  { element: "thunder", star: 4, name_en: "Bianca", name_ko: "에렌노르" },
  { element: "thunder", star: 4, name_en: "Bianca", name_ko: "레지스" },
  { element: "thunder", star: 4, name_en: "Bianca", name_ko: "람스" },
  {
    element: "thunder",
    star: 4,
    name_en: "Bianca",
    name_ko: "아우레오(크리스마스)",
  },
  { element: "thunder", star: 4, name_en: "Bianca", name_ko: "아도니" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "아리사" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "헬가" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "멜스루" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "소우시로" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "오로울" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "미아" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "시로" },
  { element: "wind", star: 4, name_en: "Bianca", name_ko: "레베카(신년)" },
  { element: "light", star: 4, name_en: "Bianca", name_ko: "키라" },
  { element: "light", star: 4, name_en: "Bianca", name_ko: "핀" },
  { element: "light", star: 4, name_en: "Bianca", name_ko: "제랄" },
  { element: "light", star: 4, name_en: "Bianca", name_ko: "디어" },
  { element: "light", star: 4, name_en: "Bianca", name_ko: "파르페" },
  { element: "light", star: 4, name_en: "Bianca", name_ko: "플로렛타" },
  { element: "dark", star: 4, name_en: "Bianca", name_ko: "리안" },
  { element: "dark", star: 4, name_en: "Bianca", name_ko: "앤디" },
  { element: "dark", star: 4, name_en: "Bianca", name_ko: "마리안네" },
  { element: "dark", star: 4, name_en: "Bianca", name_ko: "아름" },
  { element: "dark", star: 4, name_en: "Bianca", name_ko: "유웰(신년)" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "엔니" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "길슬롯" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "트레이네" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "진" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "이리스" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "메이미" },
  { element: "fire", star: 3, name_en: "Bianca", name_ko: "리릴" },
  { element: "water", star: 3, name_en: "Bianca", name_ko: "랏티" },
  { element: "water", star: 3, name_en: "Bianca", name_ko: "카이유" },
  { element: "water", star: 3, name_en: "Bianca", name_ko: "클라우스" },
  { element: "water", star: 3, name_en: "Bianca", name_ko: "엘자" },
  { element: "water", star: 3, name_en: "Bianca", name_ko: "트리스타" },
  { element: "water", star: 3, name_en: "Bianca", name_ko: "케일로스" },
  {
    element: "water",
    star: 3,
    name_en: "Bianca",
    name_ko: "챠루아(크리스마스)",
  },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "콜트" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "타티아나" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "카즈치" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "알베르토" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "쿠로" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "타이가" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "호니" },
  { element: "thunder", star: 3, name_en: "Bianca", name_ko: "유나" },
  { element: "wind", star: 3, name_en: "Bianca", name_ko: "하트리프" },
  { element: "wind", star: 3, name_en: "Bianca", name_ko: "폴스" },
  { element: "wind", star: 3, name_en: "Bianca", name_ko: "네스카" },
  { element: "wind", star: 3, name_en: "Bianca", name_ko: "챠루아" },
  { element: "wind", star: 3, name_en: "Bianca", name_ko: "에반" },
  { element: "light", star: 3, name_en: "Bianca", name_ko: "라울" },
  { element: "light", star: 3, name_en: "Bianca", name_ko: "아우레오" },
  { element: "light", star: 3, name_en: "Bianca", name_ko: "세실리아" },
  { element: "light", star: 3, name_en: "Bianca", name_ko: "마르그리트" },
  { element: "light", star: 3, name_en: "Bianca", name_ko: "코리나" },
  { element: "dark", star: 3, name_en: "Bianca", name_ko: "도로시아" },
  { element: "dark", star: 3, name_en: "Bianca", name_ko: "아딜" },
  { element: "dark", star: 3, name_en: "Bianca", name_ko: "시온" },
  { element: "dark", star: 3, name_en: "Bianca", name_ko: "아리" },
  { element: "dark", star: 3, name_en: "Bianca", name_ko: "자릴" },
  { element: "dark", star: 3, name_en: "Bianca", name_ko: "파르체" },
];
